FROM python:3.12-slim

# Install dependencies and Antithesis Python SDK
RUN pip install --no-cache-dir antithesis cffi 

# Copy the python entrypoint. It contains the lifecycle setup_complete message.
COPY ./entrypoint.py /entrypoint.py
